---
configure_dotfiles: true

configure_dock: true
dockitems_remove:
  - Calendar
  - Contacts
  - FaceTime
  - Freeform
  - Launchpad
  - Mail
  - Maps
  - Messages
  - Music
  - News
  - Notes
  - Photos
  - Podcasts
  - Reminders
  - TV
  - com.apple.FaceTime
  - com.apple.Photos
# - 'App Store'

homebrew_cask_apps:
  - firefox

homebrew_installed_packages:
  # - ansible # Installed via Pip.
  - bash-completion
  - clang-format@11
  - cmake
  - doxygen
  - gh
  - git
  - git-lfs
  - ninja
  - readline
  - ssh-copy-id
  - wget
  - zsh-history-substring-search


dotfiles_files:
  # - .zshrc
  - .gitignore
  - .inputrc
  - .osx
  # - .vimrc

dotfiles_repo: https://github.com/rpavlik/geerlingguy-dotfiles.git
